examenes/urls.py
from django.urls import path
from django.views.generic import TemplateView
from examenes import views

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard_view, name='dashboard_view'),
    path('registro', views.registro_estudiante, name='registro_estudiante'),
    path('simulacro/<int:estudiante_id>/', views.simulacro_view, name='simulacro'),
    path('simulacro/<int:estudiante_id>/categoria/<int:categoria_id>/', views.ver_preguntas_categoria, name='ver_preguntas_categoria'),
    path('resultado', TemplateView.as_view(template_name='resultado.html'), name='resultado'),    
]

simulacro_icfes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('examenes.urls'), name='examenes'),
    path('study/', include('study.urls'), name='study'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    # Serve media files during development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # Serve static files during development
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

study/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'study'
urlpatterns = [
    path('material_estudio/', views.material_estudio, name='material_estudio'),
    path('material_estudio/<int:category_id>', views.material_estudio_categoria, name='material_estudio_categoria'),
    path('material_estudio_detail/<int:material_estudio_id>', views.material_estudio_detail, name='material_estudio_detail'),
]

examenes/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    nombre = models.CharField(max_length=100)
    
    def __str__(self):
        return self.nombre
    
    class Meta:
        verbose_name_plural = "Categorias"
    
class Subject(models.Model):
    nombre = models.CharField(max_length=100)
    categoria = models.ForeignKey(Category, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.nombre} ({self.categoria.nombre})"
    
    class Meta:
        verbose_name_plural = "Materias"
    
    
class Question(models.Model):
    enunciado = models.TextField()
    materia = models.ForeignKey(Subject, on_delete=models.CASCADE)
    opcion_a = models.CharField(max_length=255)
    opcion_b = models.CharField(max_length=255)
    opcion_c = models.CharField(max_length=255)
    opcion_d = models.CharField(max_length=255)
    
    OPCIONES = [
        ('A', 'Opción A'),  
        ('B', 'Opción B'),
        ('C', 'Opción C'),
        ('D', 'Opción D'),
    ]
    respuesta_correcta = models.CharField(max_length=1, choices=OPCIONES)
    
    def __str__(self):
        return f"Pregunta: {self.enunciado[:50]}... - Respuesta: {self.respuesta_correcta}"  
    
    class Meta:
        verbose_name_plural = "Preguntas"


class User(models.Model):
    nombre = models.CharField(max_length=100)
    documento = models.CharField(max_length=20, unique=True)  # Cédula o TI
    correo = models.EmailField(unique=True)
    colegio = models.CharField(max_length=100, blank=True)
    grado = models.CharField(max_length=50, blank=True)
    
    ya_presento = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.nombre} ({self.documento})'
    
    class Meta:
        verbose_name_plural = "Usuarios"
    

class Exam(models.Model):
    estudiante = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    puntuacion = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    preguntas = models.ManyToManyField(Question, through='Answer')

    def __str__(self):
        return f'Examen de {self.estudiante.nombre} - {self.estudiante.documento} - {self.fecha.strftime("%Y-%m-%d")}'
    
    class Meta:
        verbose_name_plural = "Examenes"
    

class Answer(models.Model):
    examen = models.ForeignKey(Exam, on_delete=models.CASCADE)
    pregunta = models.ForeignKey(Question, on_delete=models.CASCADE)
    respuesta_usuario = models.CharField(max_length=1, choices=Question.OPCIONES)
    es_correcta = models.BooleanField(default=False)

    def __str__(self):
        return f'Respuesta de {self.examen.estudiante.nombre} a "{self.pregunta}"'
    
    class Meta:
        verbose_name_plural = "Respuestas"

examenes/forms.py
from django import forms
from .models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['nombre', 'documento', 'correo', 'colegio', 'grado']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'documento': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'correo': forms.EmailInput(attrs={'class': 'form-control mb-3'}),
            'colegio': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'grado': forms.TextInput(attrs={'class': 'form-control mb-3'}),
        }

examenes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Category, Subject, Question, User, Exam, Answer
from .forms import UserForm
from django.db.models import Count, Avg

# Create your views here.

def index(request):
    categorias = Category.objects.all()
    return render(request, 'index.html', {'categorias': categorias})


def dashboard_view(request):
    total_examenes = Exam.objects.count()
    promedio_por_materia = Subject.objects.annotate(
        promedio=Avg('question__answer__es_correcta')
    )
    materias = []
    for materia in promedio_por_materia:
        materias.append(
            {
                "promedio": materia.promedio * 10,
                "nombre": materia.nombre
            }
        )

    context = {
        'total_examenes': total_examenes,
        'promedio_por_materia': materias,
    }
    return render(request, 'dashboard.html', context)

def registro_estudiante(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            documento = form.cleaned_data['documento']
            
            if User.objects.filter(documento=documento, ya_presento=True).exists():
                return render(request, 'resultado.html')
            
            estudiante, creado = User.objects.get_or_create(documento=documento, defaults=form.cleaned_data)
            
            if not creado:
                for campo, valor in form.cleaned_data.items():
                    setattr(estudiante, campo, valor)
                estudiante.save()
                
            return redirect('simulacro', estudiante_id=estudiante.id)
    else:
        form = UserForm()
    
    return render(request, 'registro_estudiante.html', {'form': form})

def simulacro_view(request, estudiante_id):
    estudiante = get_object_or_404(User, id=estudiante_id)
    categorias = Category.objects.all()

    # Reiniciar la sesión si es un nuevo estudiante o no ha respondido nada
    if 'estudiante_id' not in request.session or request.session['estudiante_id'] != estudiante.id:
        request.session['estudiante_id'] = estudiante.id
        request.session['categorias_respondidas'] = []
        request.session['respuestas_parciales'] = {}
        request.session['examen_guardado'] = False
        request.session.modified = True

    respondidas = request.session.get("categorias_respondidas", [])

    # Guardar el examen si ya respondió todas
    if len(respondidas) == categorias.count():
        if not request.session.get("examen_guardado"):
            respuestas_parciales = request.session.get("respuestas_parciales", {})

            examen = Exam.objects.create(estudiante=estudiante)
            correctas = 0
            total = 0

            for respuestas in respuestas_parciales.values():
                for pregunta_id, seleccion in respuestas.items():
                    pregunta = Question.objects.get(id=pregunta_id)
                    es_correcta = seleccion == pregunta.respuesta_correcta
                    if es_correcta:
                        correctas += 1
                    total += 1

                    Answer.objects.create(
                        examen=examen,
                        pregunta=pregunta,
                        respuesta_usuario=seleccion,
                        es_correcta=es_correcta
                    )

            if total > 0:
                examen.puntuacion = round((correctas / total) * 100, 2)
                examen.save()

            estudiante.ya_presento = True
            estudiante.save()

            request.session['examen_guardado'] = True
            request.session.modified = True

            return render(request, 'resultado.html', {'puntuacion': examen.puntuacion, 'estudiante': estudiante})
        
        else:
            examen = Exam.objects.filter(estudiante=estudiante).last()
            if examen:
                puntuacion = examen.puntuacion
            else:
                puntuacion = 0

            return render(request, 'simulacro.html', {
                'puntuacion': puntuacion,
                'estudiante': estudiante,
                'categorias': categorias,
                'respondidas': respondidas,
            })

    return render(request, 'simulacro.html', {
        'estudiante': estudiante,
        'categorias': categorias,
        'respondidas': respondidas,
    })

    

def ver_preguntas_categoria(request, estudiante_id, categoria_id):
    estudiante = get_object_or_404(User, id=estudiante_id)
    categoria = get_object_or_404(Category, id=categoria_id)
    preguntas = Question.objects.filter(materia__categoria=categoria)

    # Validar que no repita categoría
    respondidas = request.session.get('categorias_respondidas', [])
    if categoria_id in respondidas:
        return redirect('simulacro', estudiante_id=estudiante.id)

    if request.method == 'POST':
        respuestas = {}
        for pregunta in preguntas:
            seleccion = request.POST.get(f'pregunta_{pregunta.id}')
            if seleccion:
                respuestas[str(pregunta.id)] = seleccion

        if respuestas:
            # Guardar respuestas en sesión
            if 'respuestas_parciales' not in request.session:
                request.session['respuestas_parciales'] = {}

            request.session['respuestas_parciales'][str(categoria_id)] = respuestas

            # Registrar categoría respondida
            if 'categorias_respondidas' not in request.session:
                request.session['categorias_respondidas'] = []
            request.session['categorias_respondidas'].append(categoria_id)

            request.session.modified = True

            return redirect('simulacro', estudiante_id=estudiante.id)

    context = {
        'estudiante': estudiante,
        'categoria': categoria,
        'preguntas': preguntas,
    }
    return render(request, 'ver_preguntas_categoria.html', context)



def responder_categoria(request, categoria_id):
    categoria = get_object_or_404(Category, id=categoria_id)
    preguntas = Question.objects.filter(categoria=categoria)
    
    # Inicializar el historial en sesión si no existe
    if "categorias_respondidas" not in request.session:
        request.session["categorias_respondidas"] = []

    if categoria_id in request.session["categorias_respondidas"]:
        return redirect("seleccionar_categoria")  # No permite repetir

    if request.method == "POST":
        respuestas = {}
        for pregunta in preguntas:
            seleccion = request.POST.get(f"pregunta_{pregunta.id}")
            if seleccion:
                respuestas[pregunta.id] = seleccion

        if respuestas:
            if "respuestas_parciales" not in request.session:
                request.session["respuestas_parciales"] = {}

            request.session["respuestas_parciales"][str(categoria_id)] = respuestas
            request.session.modified = True  

            request.session["categorias_respondidas"].append(categoria_id)
            request.session.modified = True

            return redirect("seleccionar_categoria")

    return render(request, "responder_categoria.html", {
        "categoria": categoria,
        "preguntas": preguntas,
    })

examenes/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Sistema de Evaluaciones{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <main>
        {% block container %}
        {% endblock %}
    </main>

    <footer>
        <p>&copy; 2025 - Proyecto Django Taller 2 ICFES</p>
    </footer>
</body>
</html>

examenes/templates/dashboard.html
{% extends 'base.html' %}
{% block container %}

<header>
    <h1>Dashboard de Pruebas ICFES</h1>
</header>

<div class="dashboard-contenedor">
    <div class="dashboard-card">
        <h2>Total de Exámenes Presentados</h2>
        <p>{{ total_examenes }}</p>
    </div>
</div>

<div class="dashboard-contenedor">
    {% for materia in promedio_por_materia %}
        <div class="dashboard-card promedio-card 
            {% if materia.promedio < 4 %}rojo
            {% elif materia.promedio < 6 %}anaranjado
            {% elif materia.promedio < 8 %}amarillo
            {% else %}verde
            {% endif %}">
            <h2>{{ materia.nombre }}</h2>
            <p>Promedio: {{ materia.promedio|default:"N/A" }}</p>
        </div>
    {% endfor %}
</div>

{% endblock %}

examenes/templates/index.html
{% extends 'base.html'%}
{% block container %}

<header>
    <h1>SIMULACRO PRUEBA ICFES</h1>
</header>

<div class="icfes">
        <div class="info">
            <h1>Bienvenido al Simulacro de las Pruebas ICFES</h1> <br>
            <p>Por favor haz clic en el botón para iniciar tu examen.</p>
            <a href="{% url 'registro_estudiante' %}" target="_blank" class="boton">Iniciar Simulacro</a>
            <a href="{% url 'study:material_estudio' %}" target="_blank" class="boton">Iniciar Estudio de Material</a>
        </div>
    </div>


{% endblock %}

examenes/templates/registro_estudiante.html
{% extends 'base.html' %}
{% block title %}Registro Estudiante{% endblock %}
{% block container %}

<header><h1>Registro del Estudiante</h2></header>

<div class="icfes">
    <div class="info">
        <div class="form-box">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="boton">Continuar al Simulacro</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

examenes/templates/resultado.html
{% extends 'base.html' %}
{% block container %}
<header>Resultado del Simulacro Pruebas ICFES</header>
<div class="icfes">
    <div class="info">
        
        <div class="container mt-5 text-center">
            <h1>Resultado del estudiante: {{ estudiante.nombre }} {{ estudiante.apellido }}</h1>
            <p><strong>Identificación:</strong> {{ estudiante.documento }}</p>
            <p><strong>Email:</strong> {{ estudiante.correo }}</p>
            
            <p class="lead">Tu puntuación final fue:</p>
            <h1 class="display-4 text-success">{{ puntuacion }}%</h1>
            
            <a href="{% url 'index' %}" class="btn btn-primary mt-4">Volver al inicio</a>
            
        </div>
    </div>
</div>
{% endblock %}

examenes/templates/simulacro.html
{% extends 'base.html' %}
{% block container %}
<header>Inicio del Simulacro Pruebas ICFES</header>
<div class="icfes">
    <div class="info">
        
        <div class="simulacro-contenedor">
            <h1>Bienvenid@ {{ estudiante.nombre }} {{ estudiante.apellido }}</h1>
            <p><strong>Identificación:</strong> {{ estudiante.documento }}</p>
            <p><strong>Email:</strong> {{ estudiante.correo }}</p>

            <h2>Selecciona una categoría para comenzar:</h2>
            <div class="categorias-lista">
                {% for categoria in categorias %}
                    {% if categoria.id in respondidas %}
                        <button class="boton-categoria" disabled>{{ categoria.nombre }} (Respondida)</button>
                    {% else %}
                        <a class="boton-categoria" href="{% url 'ver_preguntas_categoria' estudiante.id categoria.id %}">
                            {{ categoria.nombre }}
                        </a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

examenes/templates/ver_preguntas_categoria.html
{% extends 'base.html' %}

{% block container %}
<header>
    <h1>Preguntas de la categoría: {{ categoria.nombre }}</h1>
    <h4>Nombre del usuario: {{ estudiante.nombre }}</h4>
    <h4>Documento (T.I. / C.C.): {{ estudiante.documento }}</h4>
</header>

<style>
  .opcion {
    display: block;
    margin-bottom: 10px;
    background-color: #f0f6fc;
    padding: 10px 15px;
    border-radius: 5px;
    transition: background-color 0.2s;
  }

  .opcion:hover {
    background-color: #dceeff;
  }

  .opcion input[type="radio"] {
    margin-right: 10px;
    vertical-align: middle;
  }

  .opcion label {
    font-size: 16px;
    font-weight: normal;
    cursor: pointer;
  }

  .pregunta {
    margin-bottom: 30px;
  }
</style>


{% if preguntas %}
<form method="post">
  {% csrf_token %}
  {% for pregunta in preguntas %}
    <div class="icfes">
        <div class="info">
            <div class="pregunta">
                <p><strong>{{ forloop.counter }}. {{ pregunta.enunciado }}</strong></p>

            <div class="opcion">
                <label for="pregunta_{{ pregunta.id }}_A">
                    <input type="radio" id="pregunta_{{ pregunta.id }}_A" name="pregunta_{{ pregunta.id }}" value="A">
                    A. {{ pregunta.opcion_a }}
                </label>
            </div>
            <div class="opcion">
                <label for="pregunta_{{ pregunta.id }}_B">
                    <input type="radio" id="pregunta_{{ pregunta.id }}_B" name="pregunta_{{ pregunta.id }}" value="B">
                    B. {{ pregunta.opcion_b }}
                </label>
            </div>
            <div class="opcion">
                <label for="pregunta_{{ pregunta.id }}_C">
                    <input type="radio" id="pregunta_{{ pregunta.id }}_C" name="pregunta_{{ pregunta.id }}" value="C">
                    C. {{ pregunta.opcion_c }}
                </label>
            </div>
            <div class="opcion">
                <label for="pregunta_{{ pregunta.id }}_D">
                    <input type="radio" id="pregunta_{{ pregunta.id }}_D" name="pregunta_{{ pregunta.id }}" value="D">
                    D. {{ pregunta.opcion_d }}
                </label>
            </div>
            </div>
        </div>
    </div>
  {% endfor %}

  <button class="boton" type="submit" >Finalizar categoría</button>
</form>

{% else %}
  <p>No hay preguntas registradas en esta categoría.</p>
{% endif %}

<br>
{% endblock %}