simulacro_icfes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('examenes.urls'), name='examenes'),
    path('study/', include('study.urls'), name='study'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    # Serve media files during development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # Serve static files during development
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

study/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'study'
urlpatterns = [
    path('material_estudio/', views.material_estudio, name='material_estudio'),
    path('material_estudio/<int:category_id>', views.material_estudio_categoria, name='material_estudio_categoria'),
    path('material_estudio_detail/<int:material_estudio_id>', views.material_estudio_detail, name='material_estudio_detail'),
]

study/models.py
from django.db import models
from examenes.models import Category, Subject
from django.contrib.auth.models import User

# Create your models here.

class Subtema(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='subtemas')
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.nombre} ({self.subject.nombre})"

class MaterialEstudio(models.Model):
    subtema = models.ForeignKey(Subtema, on_delete=models.CASCADE, related_name='materiales')
    titulo = models.CharField(max_length=200)
    descripcion = models.TextField(blank=True)
    explicacion = models.TextField(blank=True)
    tipo = models.CharField(max_length=50, choices=[
        ('video', 'Video'),
        ('pdf', 'PDF'),
        ('articulo', 'Artículo'),
    ])
    enlace = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.titulo

class UserMaterialEstudio(models.Model):
    materiales = models.ForeignKey(MaterialEstudio, on_delete=models.CASCADE, related_name='materiales')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name='usuarios')
    visto = models.BooleanField(default=False)

study/views.py
from django.shortcuts import render
from .models import Subtema, MaterialEstudio, UserMaterialEstudio
from examenes.models import Category, Subject

# Create your views here.
def material_estudio(request):
    categorias = Category.objects.all()
    return render(request, 'material_estudio.html', {'categorias': categorias})


def material_estudio_categoria(request, category_id):
    materiales_estudio = MaterialEstudio.objects.filter(subtema__subject__categoria_id=category_id).all()
    context = {'materiales_estudio': materiales_estudio}
    user = request.user
    if user and user.is_authenticated:
        materiales_estudio_visto = UserMaterialEstudio.objects.filter(usuario=user, visto=True).all()
        if materiales_estudio_visto:
            material_estudio_visto = [material.materiales.id for material in materiales_estudio_visto]

            context['materiales_estudio_visto'] = material_estudio_visto
    print('material_estudio', material_estudio)

    return render(request, 'material_estudio_categoria.html', context)

def material_estudio_detail(request, material_estudio_id):
    user = request.user
    material = MaterialEstudio.objects.get(pk=material_estudio_id)

    if user.is_authenticated:
        if not UserMaterialEstudio.objects.filter(usuario=user, materiales=material).exists():
            usr_material = UserMaterialEstudio.objects.create(usuario=user, materiales=material)
            usr_material.visto = True
            usr_material.save()

    return render(request, 'material_estudio_detail.html', {'material': material})

study/templates/material_estudio.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    aca renderizaremos el material de estudio
</body>
</html>

study/templates/material_estudio_categoria.html
{% extends 'base.html' %}
{% block container %}
<header>Material de Estudio</header>
<div class="icfes">
    <div class="info">
        
        <div class="simulacro-contenedor">
            <h1>Bienvenid@</h1>

            <h2>Selecciona el subtema a repasar:</h2>
            <div class="categorias-lista">
                {% for material_estudio in materiales_estudio %}
                    <a class="boton-categoria {% if material_estudio.id in materiales_estudio_visto %} visto {% endif %}" href="{% url 'study:material_estudio_detail' material_estudio.id %}">
                        {{ material_estudio.titulo }}
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

study/templates/material_estudio_detail.html
{% extends 'base.html' %}
{% block container %}
<header>Material de Estudio</header>
<div class="icfes">
    <div class="info">
        
        <div class="simulacro-contenedor">
            <h1>Bienvenid@</h1>

            <h2>Este es el contenido del material de estudio:</h2>
            <div class="categorias-lista">
                    <p>{{ material.titulo }}</p>
                    <p>{{ material.descripcion }}</p>
                    <p>{{ material.explicacion }}</p>
                    <p>{{ material.tipo }}</p>
                    <p>{{ material.enlace }}</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}